pr-jadike?
solahidris/Project20_T2_ReactQuizApp pull request #1
Opened 2023-07-21 16:02 UTC by solahidris

2023-07-22 01:20 UTC, jakzaizzat commented on src/App.css
> -  font-size: calc(10px + 2vmin);
Why need to `calc` the font size?

2023-07-22 01:25 UTC, jakzaizzat commented on src/components/HeaderTitle.js
> +        <h2 class="text-xs py-5 px-[3rem] mt-5 mx-5 lg:mx-[30%] bg-blue-300 text-black rounded-xl">
1. No need arbitrary value for `px-[3rem]` since its `48px`. Used `px-12` instead

2. Try to avoid using percentage as a spacing margin. 
Example: `lg:mx-[30%]`

2023-07-22 01:27 UTC, jakzaizzat commented on src/components/QuizApp.js
> +import qna from "./quizData";
Used proper naming instead of `qna`

Example:

1. listOfQuestions
2. questions
3. ListOfQuestionsAndAnswers

or anything. The purpose to make it readable by other developers

2023-07-22 01:27 UTC, jakzaizzat commented on src/components/QuizApp.js
> +  };
Wrap this function inside the `useCallback`

2023-07-22 01:30 UTC, jakzaizzat commented on src/components/QuizApp.js
> +    </div>
nit: Move this code to its own component like `QuizResult.js` and accept `score` and `handleTryAgain` as a props

Example usage: 

`<Quizresult score={score} onTryAgain={handleTryAgain} />`

2023-07-22 01:31 UTC, jakzaizzat commented on src/components/CodeHow.js
> +const CodeHow = () => {
Use proper naming.

It could be something like `QuizInstructions`

2023-07-22 01:36 UTC, jakzaizzat requested changes
Nice progress! Left some comments

2023-07-22 01:36 UTC, jakzaizzat commented on src/components/QuizApp.js
> +            # {currentQuestionIndex + 1} / {qna.length}
Try avoid writing login in the template: 

Suggestions:

```js
  const currentProgress = useMemo(() => {
    return `# ${currentQuestionIndex + 1} / ${qna.length}`
  }, [currentQuestionIndex, qna.length])
```


Usage:

```jsx
         <p className="pt-5 text-xs italic text-end">
            {currentProgress}
          </p>
```

2023-07-22 01:36 UTC, jakzaizzat commented on src/components/QuizApp.js
> +                  style={{ display: "none" }} // Hide the radio input
Can used `hidden` classname instead of inline styles

https://tailwindcss.com/docs/display

2023-07-22 01:36 UTC, jakzaizzat commented on src/components/QuizApp.js
> +              </label>
Try to encapsulate this code into its own component likes `<Question/>`

2023-07-25 16:14 UTC, solahidris commented on src/components/HeaderTitle.js
> +        <h2 class="text-xs py-5 px-[3rem] mt-5 mx-5 lg:mx-[30%] bg-blue-300 text-black rounded-xl">
Done

2023-07-25 16:16 UTC, solahidris commented on src/components/QuizApp.js
> +import qna from "./quizData";
noted. done

2023-07-25 16:30 UTC, solahidris commented on src/components/QuizApp.js
> +  };
Noted. done

2023-07-25 16:33 UTC, solahidris commented on src/components/QuizApp.js
> +    </div>
Noted. Done

2023-07-25 16:35 UTC, solahidris commented on src/components/CodeHow.js
> +const CodeHow = () => {
Noted. Done

2023-07-25 16:40 UTC, solahidris commented on src/components/QuizApp.js
> +            # {currentQuestionIndex + 1} / {qna.length}
Noted. Thanks! Baru faham usememo ni haha

2023-07-25 16:44 UTC, solahidris commented on src/components/QuizApp.js
> +                  style={{ display: "none" }} // Hide the radio input
Noted. Done

2023-07-25 16:47 UTC, solahidris commented on src/components/QuizApp.js
> +              </label>
Noted. Done

2023-07-25 16:49 UTC, merged